# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da786070c2f008f084f8bb5e89ded6342e1becf43e93d24ba14f98d724012f9ef848b1a85f7a84bad2961eb461873e5a3acf88abc7855fb3501befce08da82ba

test:
  secret_key_base: d3298ee7f95685c20643dcc4589f12e9dc2fe9b7a6e5d9f792f9de9bfaa58377ff05f73ab333b78fb6018b9caac3b8d576e368d7a3d867b60222e3f4d11c5555

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
